--- 
# Exercise for setting up an ec2 server
- name: Exercise for setting up an ec2 server
 
  hosts: 44.203.103.226
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  roles: 
   - setup