--- 
# Exercise for setting up an ec2 server
- name: Exercise for setting up an ec2 server
 
  hosts: 3.91.14.223
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles: 
   - setup