--- 
# Exercise for setting up an ec2 server
- name: Exercise for setting up an ec2 server
 
  hosts: 44.203.103.226
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root 
  pre_tasks:
    - name: "Wait for 600 seconds for target connection to be reachable"
      wait_for_connection: 
  roles: 
   - setup