--- 
# Exercise for setting up an ec2 server
- name: Exercise for setting up an ec2 server
 
  hosts: 44.199.199.109 
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root 
  roles: 
   - setup